# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec file for Alpha Fixer & File Converter.

Build a standalone one-folder app with:
    pyinstaller alpha_fixer.spec

Or a single-file exe with (slower startup, same result):
    pyinstaller --onefile alpha_fixer.spec

Requires:  pip install pyinstaller
"""

import sys
from pathlib import Path

# Pull the authoritative version from src/version.py without importing Qt
_version_ns: dict = {}
exec(Path("src/version.py").read_text(), _version_ns)
_APP_VERSION = _version_ns["__version__"]

block_cipher = None

# ── collect hidden imports that PyInstaller may miss ──────────────────────────
hidden = [
    "PIL._imagingtk",
    "PIL.Image",
    "PIL.ImageFilter",
    "numpy",
    "imageio",
    "imageio.plugins",
    "imageio.plugins.pillow",
    "PyQt6.QtCore",
    "PyQt6.QtGui",
    "PyQt6.QtWidgets",
    "PyQt6.QtMultimedia",
    "src.core.alpha_processor",
    "src.core.file_converter",
    "src.core.presets",
    "src.core.settings_manager",
    "src.core.worker",
    "src.ui.main_window",
    "src.ui.alpha_tool",
    "src.ui.converter_tool",
    "src.ui.history_tab",
    "src.ui.preview_pane",
    "src.ui.settings_dialog",
    "src.ui.theme_engine",
    "src.ui.click_effects",
    "src.ui.tooltip_manager",
    "src.ui.drop_list",
    "src.ui.mouse_trail",
    "src.ui.sound_engine",
    "src.version",
]

a = Analysis(
    ["main.py"],
    pathex=[str(Path(".").resolve())],
    binaries=[],
    datas=[
        # Bundle all SVG theme files and the generated icon into the app.
        ("src/assets/svg", "src/assets/svg"),
        ("src/assets/icon.ico", "src/assets"),
    ],
    hiddenimports=hidden,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["tkinter", "unittest", "test", "tests"],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="AlphaFixerConverter",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,              # disabled: not reliably available on CI runners
    console=False,          # no console window on Windows
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon="src/assets/icon.ico",   # generated by scripts/make_icon.py
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,              # disabled: not reliably available on CI runners
    upx_exclude=[],
    name="AlphaFixerConverter",
)

# ── macOS .app bundle ─────────────────────────────────────────────────────────
if sys.platform == "darwin":
    app = BUNDLE(
        coll,
        name="AlphaFixerConverter.app",
        # icon="assets/icon.icns",
        bundle_identifier="com.pandatools.alphafixerconverter",
        info_plist={
            "CFBundleShortVersionString": _APP_VERSION,
            "NSHighResolutionCapable": True,
        },
    )
